name: Build CRM API

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: '["18.20.8", "16", "18.20.2", "18", "20", "22", "lts/*", "node"]'
        type: string
      upload-artifact:
        description: 'Upload build artifact'
        required: false
        default: false
        type: boolean

jobs:
  build-api:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-version || '["18.20.8", "16", "18.20.2", "18", "20", "22", "lts/*", "node"]') }}
    steps:
      - name: Checkout crm-api repository
        uses: actions/checkout@v4
        with:
          repository: lucidcraft-in/crm-api
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: crm-api

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: crm-api

      - name: Build API
        run: npm run build
        working-directory: crm-api

      - name: Upload API build artifact
        if: ${{ inputs.upload-artifact == true }}
        uses: actions/upload-artifact@v4
        with:
          name: crm-api-dist
          path: crm-api/dist