name: Build Web

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version'
        required: false
        default: '["18.20.8", "16", "18.20.2", "18", "20", "22", "lts/*", "node"]'
        type: string
      upload-artifact:
        description: 'Upload build artifact (skip build step if true)'
        required: false
        default: false
        type: boolean

jobs:
  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(inputs.node-version || '["18.20.8", "16", "18.20.2", "18", "20", "22", "lts/*", "node"]') }}
    steps:
      - name: Checkout web repository
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ secrets.WEB_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: web

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Build Web (dev/test)
        if: ${{ inputs.upload-artifact != true }}
        run: npm run build
        working-directory: web
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Upload Web build artifact
        if: ${{ inputs.upload-artifact == true }}
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist
