name: Build Web

on:
  workflow_dispatch:

env:
  WEB_DIR: web

jobs:
  build-web:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.20.2, 18, 20, 22, 'lts/*', 'node']
    steps:
      - name: Checkout web repository
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ secrets.WEB_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: ${{ env.WEB_DIR }}

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: ${{ env.WEB_DIR }}

      - name: Build Web
        run: npm run build
        working-directory: ${{ env.WEB_DIR }}
        env:
          NODE_OPTIONS: --max-old-space-size=4096
