name: Deploy CRM API & Web

on:
  workflow_dispatch:
    inputs:
      server_user:
        description: 'SSH username for server'
        default: 'ubuntu'

jobs:
  build-and-deploy-api:
    uses: ./.github/workflows/build-api.yaml
    with:
      node-version: '["18.20.2"]'
    secrets: inherit

  build-and-deploy-web:
    uses: ./.github/workflows/build-web.yaml
    needs: build-and-deploy-api
    with:
      node-version: '["18.20.2"]'
    secrets: inherit

  restart-services:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-api, build-and-deploy-web]
    steps:
      - name: Restart pm2 and nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/crm
            pm2 restart crm || pm2 start dist/main.js --name crm
            sudo systemctl restart nginx