name: Deploy API & Web

on:
  workflow_dispatch:
    inputs:
      server_user:
        description: 'SSH username for server'
        required: false
        default: 'ubuntu'

jobs:
  build-api:
    uses: ./.github/workflows/build-api.yaml
    with:
      node-version: '["18.20.2"]'
      upload-artifact: true
    secrets: inherit

  build-web:
    uses: ./.github/workflows/build-web.yaml
    needs: build-api
    with:
      node-version: '["18.20.2"]'
      upload-artifact: true
    secrets: inherit

  deploy-api:
    runs-on: ubuntu-latest
    needs: build-web
    steps:
      - name: Download API build artifact
        uses: actions/download-artifact@v4
        with:
          name: api-dist
          path: api/dist

      - name: Zip dist folder
        run: zip -r dist.zip dist
        working-directory: api

      - name: Ensure target directory exists and is writable
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir -p ~/${{ secrets.APP_NAME }}
            sudo chown $USER:$USER ~/${{ secrets.APP_NAME }}

      - name: Copy dist.zip to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "api/dist.zip"
          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/"
          overwrite: true

      - name: SSH Deploy API
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }} || exit 1
            if [ -f dist.zip ]; then sudo unzip -o dist.zip; else echo "dist.zip not found!"; exit 1; fi

  deploy-web:
    runs-on: ubuntu-latest
    needs: deploy-api
    steps:
      - name: Download Web project artifact
        uses: actions/download-artifact@v4
        with:
          name: web
          path: web

      - name: Set production baseURL in axios.js
        run: |
          sed -i.bak 's|baseURL: "http://localhost:3000/",|baseURL: "/",|g' src/axios/axios.js
        working-directory: web

      - name: Show axios baseURL for verification
        run: grep baseURL src/axios/axios.js
        working-directory: web

      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Build Web (production)
        run: npm run build
        working-directory: web
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Zip dist contents as client-dist.zip
        run: cd dist && zip -r ../client-dist.zip . && cd ..
        working-directory: web

      - name: Ensure web target directory exists and is writable
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir -p ~/${{ secrets.APP_NAME }}/client
            sudo chown $USER:$USER ~/${{ secrets.APP_NAME }}/client

      - name: Copy client-dist.zip to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "web/client-dist.zip"
          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/"
          overwrite: true

      - name: SSH Deploy Web
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }} || exit 1
            if [ -f client-dist.zip ]; then
              cd client || exit 1
              sudo unzip -o ../client-dist.zip
              cd ..
            else
              echo "client-dist.zip not found!"
              exit 1
            fi
  restart-services:
    runs-on: ubuntu-latest
    needs: deploy-web
    steps:
      - name: Restart pm2 and nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }}
            pm2 restart ${{ secrets.APP_NAME }} || pm2 start dist/main.js --name ${{ secrets.APP_NAME }}
            sudo systemctl restart nginx
