name: Deploy API & Web

on:
  workflow_dispatch:
    inputs:
      server_user:
        description: 'SSH username for server'
        required: false
        default: 'ubuntu'

jobs:
  build-and-deploy-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout api repository
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ secrets.API_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: api

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.20.8

      - name: Install dependencies
        run: npm install
        working-directory: api

      - name: Build API
        run: npm run build
        working-directory: api

      - name: Zip dist folder
        run: zip -r dist.zip dist
        working-directory: api

      - name: Ensure target directory exists and is writable
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir ~/${{ secrets.APP_NAME }}
            sudo chown $USER:$USER ~/${{ secrets.APP_NAME }}

      - name: Copy dist.zip to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "api/dist.zip"
          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/"
          overwrite: true

      - name: SSH Deploy API
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }} || exit 1
            if [ -f dist.zip ]; then sudo unzip -o dist.zip; else echo "dist.zip not found!"; exit 1; fi

  build-and-deploy-web:
    runs-on: ubuntu-latest
    needs: build-and-deploy-api
    steps:
      - name: Checkout web repository
        uses: actions/checkout@v4.2.2
        with:
          repository: ${{ secrets.WEB_REPO }}
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          path: web

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 18.20.8

      - name: Install dependencies
        run: npm install
        working-directory: web

      - name: Set production baseURL in axios.js
        run: |
          sed -i.bak 's|baseURL: "http://localhost:3000/",|baseURL: "/",|g' src/axios/axios.js
        working-directory: web

      - name: Show axios baseURL for verification
        run: grep baseURL src/axios/axios.js
        working-directory: web

      - name: Build Web
        run: npm run build
        working-directory: web

      - name: Zip dist contents as client-dist.zip
        run: cd dist && zip -r ../client-dist.zip . && cd ..
        working-directory: web

      - name: Ensure web target directory exists and is writable
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            sudo mkdir -p ~/${{ secrets.APP_NAME }}/client
            sudo chown $USER:$USER ~/${{ secrets.APP_NAME }}/client

      - name: Copy client-dist.zip to server
        uses: appleboy/scp-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "web/client-dist.zip"
          target: "/home/${{ github.event.inputs.server_user }}/${{ secrets.APP_NAME }}/client/"
          overwrite: true

      - name: SSH Deploy Web
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }}/client || exit 1
            if [ -f client-dist.zip ]; then sudo unzip -o client-dist.zip; else echo "client-dist.zip not found!"; exit 1; fi

  restart-services:
    runs-on: ubuntu-latest
    needs: [build-and-deploy-api, build-and-deploy-web]
    steps:
      - name: Restart pm2 and nginx
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ github.event.inputs.server_user }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/${{ secrets.APP_NAME }}
            pm2 restart ${{ secrets.APP_NAME }} || pm2 start dist/main.js --name ${{ secrets.APP_NAME }}
            sudo systemctl restart nginx